on:
  workflow_call:
    inputs:
      region:
        description: region to run in
        type: string
      account:
        description: account to run in
        type: string
      path:
        description: Relative path under $GITHUB_WORKSPACE for the terraform workspace
        type: string
jobs:
  check:
    concurrency:
      group: ${{ github.ref }}-${{ inputs.path }}
      cancel-in-progress: true
    runs-on: reejig-development-ap-southeast-2
    env:
      REGION: ${{ inputs.region }}
      ACCOUNT: ${{ inputs.account }}
    steps:
      - uses: actions/checkout@v3
      - uses: reejig/github-actions/aws/login@v2
        with:
          region: ${{ env.REGION }}
          account: ${{ env.ACCOUNT }}
      - uses: reejig/github-actions/terraform/setup@v1
      - uses: reejig/github-actions/terraform/check@v1
        with:
          path: ${{ inputs.path }}
  apply:
    concurrency:
      group: ${{ inputs.path }}[]]]-reejig-development
      cancel-in-progress: true
    runs-on: reejig-development-ap-southeast-2
    needs:
      - check
    env:
      REGION: ap-southeast-2
      ACCOUNT: reejig-development
    steps:
      - uses: actions/checkout@v1
      - uses: reejig/github-actions/aws/login@v2
        with:
          region: ${{ env.REGION }}
          account: ${{ env.ACCOUNT }}
      - uses: reejig/github-actions/terraform/setup@v1
      - uses: reejig/github-actions/terraform/plan@v1
        with:
          path: ${{ inputs.path }}
      #! - uses: reejig/github-actions/terraform/apply@v1
      #!   with:
      #!     path: ${{ inputs.path }}
        #TODO: put this logic in later
        #if: ${{ ( github.ref == 'refs/heads/master' && github.event.inputs.run_apply == '' ) || ( github.event.inputs.run_apply == 'true' && ( github.event.inputs.environments == 'all' || github.event.inputs.environments == 'dev' )) }}
        #with:
        #  slack_webhook: ${{ secrets.SLACK_WEBHOOK }}