on:
  workflow_call:
    inputs:
      env:
        description: environment name
        type: string
      matrix:
        description: matrix
        type: string
      path:
        description: Relative path under $GITHUB_WORKSPACE for the terraform workspace
        type: string
jobs:
  plan:
    concurrency:
      group: ${{ inputs.path }}-${{ matrix.account }}-${{ matrix.region }}
      cancel-in-progress: false
    strategy:
      fail-fast: false
      matrix: ${{ inputs.matrix }}
    runs-on: ${{ matrix.account }}-${{ matrix.region }}
    env:
      REGION: ${{ matrix.region }}
      ACCOUNT: ${{ matrix.account }}
      ENV: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v1
      - uses: reejig/github-actions/aws/login@v2
        with:
          region: ${{ env.REGION }}
          account: ${{ env.ACCOUNT }}
      - uses: reejig/github-actions/terraform/setup@v1
      - uses: reejig/github-actions/terraform/plan@v1
        with:
          path: ${{ inputs.path }}
          tf_plan_id: ${{ github.run_id }}-tfplan-${{ env.ACCOUNT }}-${{ env.REGION }}
  apply:
    needs: plan
    concurrency:
      group: ${{ inputs.path }}-${{ matrix.account }}-${{ matrix.region }}
      cancel-in-progress: false
    strategy:
      fail-fast: false
      matrix: ${{ inputs.matrix }}
    runs-on: ${{ matrix.account }}-${{ matrix.region }}
    env:
      REGION: ${{ matrix.region }}
      ACCOUNT: ${{ matrix.account }}
      ENV: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v1
      - uses: reejig/github-actions/aws/login@v2
        with:
          region: ${{ env.REGION }}
          account: ${{ env.ACCOUNT }}
      - uses: reejig/github-actions/terraform/setup@v1
      - uses: reejig/github-actions/terraform/apply@v1
        with:
          path: ${{ inputs.path }}
          tf_plan_id: ${{ github.run_id }}-tfplan-${{ env.ACCOUNT }}-${{ env.REGION }}
      #! - uses: reejig/github-actions/terraform/destroy@v1
      #!   with:
      #!     path: ${{ inputs.path }}
      #! - uses: reejig/github-actions/terraform/apply@v1
      #!   with:
      #!     path: ${{ inputs.path }}
        #TODO: put this logic in later
        #if: ${{ ( github.ref == 'refs/heads/master' && github.event.inputs.run_apply == '' ) || ( github.event.inputs.run_apply == 'true' && ( github.event.inputs.environments == 'all' || github.event.inputs.environments == 'dev' )) }}
        #with:
        #  slack_webhook: ${{ secrets.SLACK_WEBHOOK }}